config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'landing_pages#home'
  resources :users
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  resources :courses
  resources :transactions
  resources :syllabuses
  
end

app/models/user.rb
class User < ApplicationRecord
    has_many :course_enrollments
    has_many :course_publishes
    has_many :feedbacks
    has_many :transactions

    validates :email, uniqueness: true
    validates :password_digest, length: { minimum: 8, too_short: "Password is too short" }
    validates :contact, length: { maximum: 10 }

    has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :set_user, only: [:show]
    before_action :set_publish, only: [:show]
    before_action :set_enrollment, only: [:show]

    def index
    end

    def show
    end
    
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            flash[:notice] = "Welcome to Course Management System #{@user.uname}, you have successfully signed up"
            # redirect_to root_path
            redirect_to login_path
        else 
            render 'new'
        end
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            flash[:notice] = "#{@user.uname} your has been updated"
            # redirect_to root_path
            redirect_to @user
        else 
            render :edit, status: :unprocessable_entity
        end
    end

    private
    
    def user_params
        params.require(:user).permit(:uname, :email, :password, :contact)
    end

    def set_user
        @user = User.find(params[:id])
    end

    def set_publish
        @course_publishe = CoursePublish.where("user_id = ? ", params[:id])
    end

    def set_enrollment
        @course_enrollment = CourseEnrollment.where("user_id = ? ", params[:id])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with model: user do |form| %>
    <table class="form-table">
        <tr>
            <td><%= form.label :uname, "Enter Your Name: " %></td>
            <td><%= form.text_field :uname, placeholder: "Steve Rogers" %></td>
        </tr>
        <tr>
            <td><%= form.label :email, "Enter Your Email: " %></td>
            <td><%= form.email_field :email, placeholder: "rogerssteve@example.com" %></td>
        </tr>
        <tr>
            <td><%= form.label :password, "Enter Your Password: " %></td>
            <td><%= form.password_field :password, placeholder: "**********" %></td>
        </tr>
        <tr>
            <td><%= form.label :contact, "Enter Your Contact: " %></td>
            <td><%= form.text_field :contact, placeholder: "9878765454" %></td>
        </tr>
        <tr><td colspan="2" class="button-centre"><%= form.submit class: "button" %></td></tr>
    </table>
<% end %>

app/views/users/edit.html.erb
<%= render partial: "shared/navigation" %>

<h1>Edit Your Details Here</h1>

<%= render "form", user: @user %>

app/views/users/index.html.erb
<h1>Welcome User</h1>

app/views/users/new.html.erb
<h1>Welcome to Sign Up Page</h1>

<%= render "form", user: @user %>

app/views/users/show.html.erb
<%= render partial: "shared/navigation" %>
<h1>Welcome <i><%= @user.uname %> 👋 </i> </h1>
<div class="course-bought">
    <h2 class="second-header">Course Bought</h2>
    <table class="course-bought-table">
        <tr>
            <th>Course Name</th>
            <th>Course Published By</th>
            <th>Bought On</th>
            <th>Valid Till</th>
            <th>Click To Learn</th>
        </tr>
        <% if @course_enrollment.count != 0 %>
            <% (@course_enrollment).each do |i|%>
                <tr> 
                    <td><%= Course.find(i.course_id).cname %></td>
                    <% u_id = CoursePublish.find_by(course_id: i.course_id).user_id %>
                    <td><%= User.find(u_id).uname %></td>
                    <td><%= Transaction.find_by(user_id: i.user_id, course_id: i.course_id).created_at %></td>
                    <td><%= i.valid_till %></td>
                    <td><%= button_to "Click Here", syllabus_path, method: :get, params: { course_id: i.course_id }, class: "button"  %></td>
                </tr>
            <% end %>
        <% else %>
           <tr>
            <td colspan="5">
                <div class="nothing">
                    <h4>You haven't bought any course till now.</h4>
                    <p>To buy a course visit <%= link_to "Buy Course", new_transaction_path %></p>
                </div>
            </td>
           </tr>
        <% end %>
    </table>
</div>
<div class="course-publish">
    <h2 class="second-header">Course Published</h2>
    <table class="course-publish-table">
        <tr>
            <th>Course Name</th>
            <th>Course Rating</th>
            <th>Enrollment Count</th>
            <th>Edit Syllabus</th>
            <th>Delete Course</th>
        </tr>
        
        <% if @course_publishe.count != 0  %>
            <% (@course_publishe).each do |i|%>
                <tr> 
                    <td><%= Course.find(i.course_id).cname %></td>
                    <td><%= Course.find(i.course_id).rating %></td>
                    <td><%= CourseEnrollment.where(course_id: i.course_id).count %></td>
                    <td><%= button_to "Edit Syllabus", syllabus_path, method: :get, params: { course_id: i.course_id }, class: "button"  %></td>
                    <td><%= button_to "Delete Course", course_path(i.course_id), method: :delete, class: "button"  %></td>
                </tr>
            <% end %>
        <% else %>
           <tr>
            <td colspan="5">
                <div class="nothing">
                    <h4>You haven't published any course till now.</h4>
                    <p>To buy a course visit <%= link_to "Publish Course",new_course_path %></p>
                </div>
            </td>
           </tr>
        <% end %>
    </table>
</div>