config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'landing_pages#home'
  resources :users
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  resources :courses
  resources :transactions
  resources :syllabuses
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/certificate.rb
class Certificate < ApplicationRecord
    belongs_to :course_enrollment
end

app/models/course.rb
class Course < ApplicationRecord
    validates :cname, uniqueness: true

    has_many :course_enrollments, dependent: :delete_all
    has_many :course_publishes, dependent: :delete_all
    has_many :transactions
    has_many :feedbacks, dependent: :delete_all
    has_many :syllabuses, dependent: :delete_all
end

app/models/course_enrollment.rb
class CourseEnrollment < ApplicationRecord
    belongs_to :user
    belongs_to :course

    has_one :progress
    has_one :certificate
end

app/models/course_publish.rb
class CoursePublish < ApplicationRecord
    self.primary_keys = :user_id, :course_id
    
    belongs_to :user
    belongs_to :course
end

app/models/feedback.rb
class Feedback < ApplicationRecord
    belongs_to :user
    belongs_to :course

    validates :review, length: { maximum: 500, too_long: "Word limit only upto 500 characters" }
end

app/models/progress.rb
class Progress < ApplicationRecord
    belongs_to :course_enrollment
end

app/models/syllabus.rb
class Syllabus < ApplicationRecord
    belongs_to :course
end

app/models/transaction.rb
class Transaction < ApplicationRecord
    belongs_to :user
    belongs_to :course
end

app/models/user.rb
class User < ApplicationRecord
    has_many :course_enrollments
    has_many :course_publishes
    has_many :feedbacks
    has_many :transactions

    validates :email, uniqueness: true
    validates :password_digest, length: { minimum: 8, too_short: "Password is too short" }
    validates :contact, length: { maximum: 10 }

    has_secure_password
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

    before_action :authorize_user

    def index
    end

    def new
        @course = Course.new
        @course_publishe = CoursePublish.new
    end

    def create
        @course = Course.new(course_params)
        if @course.save
            flash[:notice] = "Course named #{@course.cname}, added successfully. Please add syllabus model"
            # redirect_to root_path
            @course_publishe = CoursePublish.create(user_id: @user.id, course_id: @course.id)
            @course_publishe.save
            redirect_to new_syllabus_path(:course_id => @course.id)
        else 
            render 'new'
        end
    end


    def destroy
        @course = Course.find(params[:id])
        CoursePublish.find_by(course_id: @course.id).destroy
        if CourseEnrollment.find_by(course_id: @course.id)
            CourseEnrollment.find_by(course_id: @course.id).destroy
        end
        if Syllabus.find_by(course_id: @course.id)
            Syllabus.find_by(course_id: @course.id).destroy
        end
        @course.destroy

        flash[:notice] = "Course deleted successfully."
        redirect_to @user

    end

    private

    def course_params
        params.require(:course).permit(:cname, :description, :price, :duration, :rating, :category, :validity, :drafting_status)
    end
    
    def authorize_user
        user_session_id = session[:user_id]
        @user = User.find(user_session_id)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:notice] = "Logged in Succesfully"
            redirect_to user
        else
            flash.now[:notice] = "There was something wrong with your login credentials"
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = "Logged out"
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :set_user, only: [:show]
    before_action :set_publish, only: [:show]
    before_action :set_enrollment, only: [:show]

    def index
    end

    def show
    end
    
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            flash[:notice] = "Welcome to Course Management System #{@user.uname}, you have successfully signed up"
            # redirect_to root_path
            redirect_to login_path
        else 
            render 'new'
        end
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            flash[:notice] = "#{@user.uname} your has been updated"
            # redirect_to root_path
            redirect_to @user
        else 
            render :edit, status: :unprocessable_entity
        end
    end

    private
    
    def user_params
        params.require(:user).permit(:uname, :email, :password, :contact)
    end

    def set_user
        @user = User.find(params[:id])
    end

    def set_publish
        @course_publishe = CoursePublish.where("user_id = ? ", params[:id])
    end

    def set_enrollment
        @course_enrollment = CourseEnrollment.where("user_id = ? ", params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/landing_pages_helper.rb
module LandingPagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/syllabuses_helper.rb
module SyllabusesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Course-Management-System</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,400;0,500;1,600&display=swap" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render partial: "shared/flash" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_flash.html.erb
<div class="container" style=" display: inline; position: absolute; top: 10%; right: 0; width: auto; text-align: center; margin: 0.8rem;">
    <% if flash[:notice] %>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <%= flash[:notice] %>
            <button type="button" class="close button-flash" data-dismiss="alert" aria-label="Close" style=" border: none; background: transparent; margin-left: 1rem; font-size: 1.5rem;font-weight: 600;">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    <% end %>
</div>

app/views/shared/_navigation.html.erb
<header>
    <% @user = User.find_by(id: session[:user_id]) %>
    <div class="main-header">
        <div class="left-header">
            <nav>
                <ul class="nav-list">
                    <li><%= link_to "Home", @user %></li>
                    <li><%= link_to "Publish Course", new_course_path %></li>
                    <li><%= link_to "Buy Course", new_transaction_path %></li>
                    <li><%= link_to "Edit Profile", edit_user_path(@user.id) %></li>
                    <li><%= link_to "My Orders", transaction_path(@user.id) %></li>
                </ul>
            </nav>
        </div>
        <div class="right-header">
            <span>Hello, <i><%= @user.uname %></i></span>
            <span><%= link_to "Sign Out", logout_url %></span>
        </div>
    </div>
</header>